ALTER TABLE 02_zone ADD COLUMN raoprop_id INT(11) NULL;

UPDATE 02_zone SET name = 'Nusa Tenggara Barat (NTB)' WHERE name = 'Nusa Tenggara Barat';
UPDATE 02_zone SET name = 'Nusa Tenggara Timur (NTT)' WHERE name = 'Nusa Tenggara Timur';
UPDATE 02_zone SET name = 'Bangka Belitung' WHERE name = 'Kepulauan Bangka Belitung';
UPDATE 02_zone SET name = 'DKI Jakarta' WHERE name = 'Jakarta';
UPDATE 02_zone SET name = 'Nanggroe Aceh Darussalam (NAD)' WHERE name = 'Aceh';

UPDATE 02_zone SET raoprop_id ='1' WHERE name = 'Bali';
UPDATE 02_zone SET raoprop_id ='2' WHERE name = 'Bangka Belitung';
UPDATE 02_zone SET raoprop_id ='3' WHERE name = 'Banten';
UPDATE 02_zone SET raoprop_id ='4' WHERE name = 'Bengkulu';
UPDATE 02_zone SET raoprop_id ='5' WHERE name = 'DI Yogyakarta';
UPDATE 02_zone SET raoprop_id ='6' WHERE name = 'DKI Jakarta';
UPDATE 02_zone SET raoprop_id ='7' WHERE name = 'Gorontalo';
UPDATE 02_zone SET raoprop_id ='8' WHERE name = 'Jambi';
UPDATE 02_zone SET raoprop_id ='9' WHERE name = 'Jawa Barat';
UPDATE 02_zone SET raoprop_id ='10' WHERE name = 'Jawa Tengah';
UPDATE 02_zone SET raoprop_id ='11' WHERE name = 'Jawa Timur';
UPDATE 02_zone SET raoprop_id ='12' WHERE name = 'Kalimantan Barat';
UPDATE 02_zone SET raoprop_id ='13' WHERE name = 'Kalimantan Selatan';
UPDATE 02_zone SET raoprop_id ='14' WHERE name = 'Kalimantan Tengah';
UPDATE 02_zone SET raoprop_id ='15' WHERE name = 'Kalimantan Timur';
UPDATE 02_zone SET raoprop_id ='16' WHERE name = 'Kalimantan Utara';
UPDATE 02_zone SET raoprop_id ='17' WHERE name = 'Kepulauan Riau';
UPDATE 02_zone SET raoprop_id ='18' WHERE name = 'Lampung';
UPDATE 02_zone SET raoprop_id ='19' WHERE name = 'Maluku';
UPDATE 02_zone SET raoprop_id ='20' WHERE name = 'Maluku Utara';
UPDATE 02_zone SET raoprop_id ='21' WHERE name = 'Nanggroe Aceh Darussalam (NAD)';
UPDATE 02_zone SET raoprop_id ='22' WHERE name = 'Nusa Tenggara Barat (NTB)';
UPDATE 02_zone SET raoprop_id ='23' WHERE name = 'Nusa Tenggara Timur (NTT)';
UPDATE 02_zone SET raoprop_id ='24' WHERE name = 'Papua';
UPDATE 02_zone SET raoprop_id ='25' WHERE name = 'Papua Barat';
UPDATE 02_zone SET raoprop_id ='26' WHERE name = 'Riau';
UPDATE 02_zone SET raoprop_id ='27' WHERE name = 'Sulawesi Barat';
UPDATE 02_zone SET raoprop_id ='28' WHERE name = 'Sulawesi Selatan';
UPDATE 02_zone SET raoprop_id ='29' WHERE name = 'Sulawesi Tengah';
UPDATE 02_zone SET raoprop_id ='30' WHERE name = 'Sulawesi Tenggara';
UPDATE 02_zone SET raoprop_id ='31' WHERE name = 'Sulawesi Utara';
UPDATE 02_zone SET raoprop_id ='32' WHERE name = 'Sumatera Barat';
UPDATE 02_zone SET raoprop_id ='33' WHERE name = 'Sumatera Selatan';
UPDATE 02_zone SET raoprop_id ='34' WHERE name = 'Sumatera Utara';
